name: services
description: A service booking application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  permission_handler: ^11.3.1
  android_alarm_manager_plus: ^3.0.1
  intl: ^0.20.0
  table_calendar: ^3.2.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/default_avatar.png
    - assets/images/cleaning.png
    - assets/images/mechanic.png
    - assets/images/delivery.png
    - assets/images/banner1.png
    - assets/images/banner2.png
    - assets/images/banner3.png 